# List all available manifests and generate a list for index.html
# Usage: .\list_manifests.ps1

$manifestDir = Join-Path $PSScriptRoot "manifest"
$outputFile = Join-Path $PSScriptRoot "manifest_list.js"

if (-not (Test-Path $manifestDir)) {
    Write-Host "'manifest' folder does not exist!" -ForegroundColor Red
    exit 1
}

$manifestFiles = Get-ChildItem -Path $manifestDir -Filter "*.json" | Sort-Object Name

if ($manifestFiles.Count -eq 0) {
    Write-Host "No manifest files found in the 'manifest' folder" -ForegroundColor Yellow
    exit 0
}

Write-Host "Found manifests:" -ForegroundColor Cyan
$manifestList = @()

foreach ($file in $manifestFiles) {
    try {
        $content = Get-Content -Path $file.FullName -Raw | ConvertFrom-Json
        $manifestList += "manifest/$($file.Name)"
        Write-Host "  - $($file.Name) ($($content.name) v$($content.version))" -ForegroundColor Green
    } catch {
        Write-Host "  - $($file.Name) (ERROR: invalid JSON file)" -ForegroundColor Red
    }
}

# Generate the JavaScript file for index.html
$manifestListJs = $manifestList | ForEach-Object { "  '$_'," }
$jsContent = @"
// Available manifests - Auto-generated by list_manifests.ps1
// Do not edit manually. Re-run list_manifests.ps1 to regenerate.
export const MANIFEST_FILES = [
$($manifestListJs -join "`n")
];
"@

Set-Content -Path $outputFile -Value $jsContent -Encoding UTF8
Write-Host ""
Write-Host "manifest_list.js created with $($manifestList.Count) manifests" -ForegroundColor Green
Write-Host "You can now include this file in index.html" -ForegroundColor Cyan

