// Available manifests - Auto-generated by sync_firmware.ps1
// Do not edit manually. Re-run sync_firmware.ps1 to regenerate.
export const MANIFEST_FILES = [
  'manifest/manifest_Fysetc_E4_10.24c.json',
];
